import Route from '@ember/routing/route';
export default class DogRoute extends Route {
  async model() {
    // random names to give to images of random dogs
    const dogoNames = [
      'Violet',
      'Gimli',
      'Tobie',
      'Bayou',
      'Rusty',
      'Cara',
      'Nettles',
      'Elsa',
      'TugBoat',
      'Benny',
      'Tbone',
      'Bailey Juliet Borgen',
      'Ritva',
      'Cy Murray',
      'Morrison',
      'Tennie',
      'Terra',
      'Nani',
      'Blondie',
      'Coats',
      'Emmygirl',
      'Minny',
      'SimonRabbit',
      'Chara',
      'Zoey',
      'Star',
      'Cooper Copper Steve',
      'Garrett',
      'Berkeley',
      'Loki',
      'Scout Montes',
      'Lance(lot)',
      'Kidalee Divey',
      'Sullivan',
      'Jaxxson',
      'Robi',
      'Big Moe',
      'Mr Chubs',
      'Moxee',
      'Allii',
      'Vince',
      'Souris',
      'Smokey Joe',
      'Butterball',
      'Fergus Falls',
      'Zora',
      'Vera',
      'Charleston',
      'Julian',
      'Churchill',
      'Butch',
      'Ruffy',
      'Kalypso the Destroyer',
      'Rooby Doo',
      'PupBain',
      'Gunter',
      'Coco Puff',
      'Nia',
      'Mango',
      'Happy Jack',
      'Guapo',
      'Buddy Mercer',
      'Shortstop',
      'Anastasia',
      'Dindi',
      'Avery',
      'Tyee',
      'Bethany',
      'Patrick',
      'Shitake',
      'Montlake',
      'Betsey',
      'Odin Hawthorne Bell',
      'Wensel',
      'Queeny',
      'Cornflake',
      'Ollie (also goes by CB)',
      'Bebop',
      'Houdini',
      'locita',
      'Spud',
      'Lillie',
      'Benita',
      'Avi',
      'Bonita',
      'Gigi Bella',
      'Dear Prudence',
      'Archimedes',
      'Qiviut',
      'Koda St. George',
      'Abilene',
      'Cookie Diane',
      'Chili Pepper',
      'Maxyne',
      'Pete',
      'Secret',
      'Dozer',
      'Gem',
      'Bullett',
      'Hardie',
      'Jesse Mae',
      'Ianto',
      'Blackie',
      'Eli Flory',
      'Nissa',
      'Missus P',
      'Luc',
      'Beauregard',
      'Cruz',
      'Alli',
      'Presto VII',
      'Towoe',
      'Abi',
      'Caramel',
      'Yetti Kush',
      'Woody',
      'Irie',
      'Jarl',
      'Oriax',
      'Bartlet',
      'L.B.',
      'Zena',
      'Pippi',
      'Quest',
      'Aggie',
      'Twinkie',
      'Beau Ty',
      'Andy',
      'Yaya',
      'Mocca',
      'Hoover',
      'Stolley',
      'Killer',
      'Amber',
      'Lupin',
      'Carlyle',
      'Hagen',
      'Yugi',
      'Kula',
      'Hjalmar',
      'Teddy Boy',
      'Marzipan',
      'Bengie',
      'Esme Swigart',
      'Indy',
      'Kay Dee',
      'Shug',
      'Cleveland',
      'Baker Fabian Will',
      'Cuddy',
      'Iggy',
      'Ingmar',
      'Troble',
      'Pumpkin',
      'Mr BoJangles',
      'Kwabi',
      'Tuffy',
      'Jul',
      'Birdy',
      'Franz',
      'Sabine',
      'Minstrel (Mini)',
      'Filly',
      'Kumi',
      'Aregtum',
      'Kaiju',
      'Macchia',
      'Sparkle',
      'Dodger',
      'Mischa',
      'Cricket Jones',
      'Lazarus',
      'Kado Love',
      'Dixie Mae',
      'Primo',
      'Howler',
      'Astra',
      'Ezti',
      'Kane',
      'Daman',
      'Waco',
      'Jadzia Dax',
      'Big B',
      'Olive Legg',
      'Spokie Luc',
      'Colin',
      'Skye',
      'Donner',
      'Icey',
      'Duggie',
      'Pilot',
      'Bosco',
      'Tango',
      'Boscoe',
      'Doug',
      'Annie Garcia',
      'Doll',
      'Brindy',
      'Kita',
      'Gioia',
      'Amarok',
      'Libby Montana',
      'Timo',
      'Flavia',
      'Haines',
      'Gibson',
      'Fraley',
      'Ladybird "Birdie"',
      'Teddy',
      'goblin',
      'Lewis Lebowski',
      'Kulit',
      'Ella Mae',
      'Ace Frank',
      'Buddyboy',
      'Fen',
      'Larkspur',
      'Molly Snapper',
      'Odessa',
      'Tansy',
      'Bennett',
      'Kayuh',
      'Titus',
      'Hayes Kral',
      'Mae Valentine',
      'Chui',
      'Morton',
      'Ralph Akira Lindgren',
      'Booray',
      'Fury',
      'Mora',
      'Kisses',
      'Ben',
      'Zarya',
      'Rodey',
      'Millie Josephine Waffles Naslund',
      'Arrakis',
      'Biscotti',
      'LeRoy',
      'K. C.',
      'Rooney',
      'Gabe',
      'Chobo',
      'Stormy',
      'Scrubs',
      'Pashka',
      'Katy',
      'Le Mops',
      'Codi',
      'Mikko',
      'Mario',
      'Bowman',
      'Kyuri',
      'Lavern',
      'Rux',
      'Jinger Eriksson',
      'Madiba',
      'Pula',
      'Robson',
      'Giana',
      'Jellybean',
      'Sharik',
      'Zage',
      'Letty',
      'George Booker',
      'Chapman',
      'Sassie',
      'Jazzy',
      'Playa',
      'Springer',
      'Quesadilla',
      'Scarlotte',
      'Bob Barker',
      'Maysen',
      'Angus Leroy',
      'Kody',
      'Linda',
      'Marcus',
      'Willow',
      'Jinks',
      'Zigfried',
      'Cody Rose',
      'Little dog',
      'Friedrich',
      'Inga',
      'Ciaran',
      'Tikka Bear',
      'Domingo Placido',
      'Mosby',
      'Beverly',
      'Clark',
      'Magic',
      'Zoei',
      'Lottie',
      'Achoo',
      'Fritz',
      "Reese's",
      'Sami',
      'Niji',
      'Oliver',
      'Paris',
      'Laszlo Lev',
      'Laki',
      'Keenyah',
      'Mr. Frederick Oatmeal Popper',
      'Buddy holly',
      'Lilly',
      'Chong',
      'Porkchop',
      'Martianna',
      'Moe Williams',
      'Princess Cupcake',
      'Pillin',
      'Beebee',
      'Buckminster Fuller',
      'Jessa',
      'Arlo',
      'Saki',
      "Maple Leaf's Maxwell",
      'Mucho',
      'Finnley Allen',
      'Lefty',
      'Zaiden',
      'Solstice',
      'Inuyasha',
      'Fauxy',
      'Bode',
      'Zeke',
      'Koro',
      'Baloo',
      'Hector',
      'Zed',
      'Lilly Liu',
      'French Fry',
      'Alki Jack',
      'Bootsie',
      'Kim',
      'Coty',
      'Elska',
      'P-Jo',
      'Ned',
      'Thomas',
      'Lumiere',
      'Pretzel',
      'Prinz (Farley)',
      'Tag',
      'Rel Dean',
      'Granite',
      'Brodie',
      'Raspberry',
      'Knoopi',
      'Snorkels',
      "P'Nut",
      'Stephanie',
      'Nash',
      'Mopsie',
      'Diesel',
      'Mitz',
      'Neahkahnie',
      'Linus (Alastor Moody)',
      'Henni',
      'Suzy Q',
      'McGrupp',
      'Spencer',
      'Bronx',
      'Power',
      'Finnian',
      'Carlin',
      'Tasi',
      'George Franklin',
      'Mary Puppins',
      'Keiki',
      'BeBe',
      'Dolly',
      'Hadleigh',
      'Dusti',
      'Drake Bugatti Viernes',
      'Ozzie (Oswald)',
      'Reya',
      'Gumbo',
      'Cinco',
      'Lukie',
      'Tina Turner',
      'Banks',
      'Coco Bella',
      'Talulah',
      'Lambie',
      'Brona',
      'Yogi Gunner Hare',
      'Shackleton',
      'Tiko',
      'Tosha',
      'Dorah',
      'Whitman',
      'Paco',
      'Oliver Dublin',
      'Marie Louise',
      'Hadji',
      'Bastian',
      'Vader',
      'Cezanne',
      'Chin Lee',
      'Bingo',
      'Ridley',
      'Lupa Burdy',
      'Ono',
      'Dennie',
      'Mamacita',
      'Herbert',
      'Manju',
      'Margot',
      'Bocca',
      'Patches',
      'Aki Apollo',
      'Kengie',
      'Fauna',
      'Laszlo',
      'Tabatha',
      'Tizzy',
      'Billygoat',
      'Moki',
      'Kylie',
      'Mele',
      'Matzoh',
      'Bhima',
      'Zena Yamanaka',
      'Cheese',
      'Jermaine',
      'Bu"ons Meorge Raas-Bergquist',
      'Gideon',
      'Snaps',
      'Hannah Belle',
      'Nittany',
    ];

    const dogImageApiUrl = 'https://dog.ceo/api/breeds/image/random/10';
    const dogImagesResponse = await fetch(dogImageApiUrl);
    const dogImagesJson = await dogImagesResponse.json();
    let data = [];
    for (let i = 0; i < 10; i++) {
      let ranIndex = Math.floor(Math.random() * dogoNames.length);
      let randomName = dogoNames[ranIndex];
      data.push({ name: randomName, imageUrl: dogImagesJson.message[i] });
    }
    return data;
  }
}
